#!/usr/bin/env python3
"""Deprecated. The 54-fish WWF catalogue seed is generated by:

    python scripts/generate_wwf_catalogue_54.py
"""

from __future__ import annotations

import sys

print(
    "Use backend/scripts/generate_wwf_catalogue_54.py — "
    "this script would overwrite the 54-fish WWF seed.",
    file=sys.stderr,
)
raise SystemExit(1)
