-- SukaSeafood I1 — reference seed 01: location
--
-- Malaysian states and districts, derived from the OpenDOSM PriceCatcher
-- premise lookup — the only geography PriceCatcher actually reports against.
-- Seeding from that lookup (rather than a generic list of Malaysian districts)
-- guarantees every price row the ETL loads can resolve to a location_id.
--
-- Keys come from suka_uuid5(), so ids are identical in local Docker, CI and
-- Supabase. Idempotent: safe to re-run.
--
-- Requires: schema/i1_functions_indexes.sql

BEGIN;

-- 16 states / federal territories
INSERT INTO location (location_id, parent_location_id, level, state_name, district_name, active)
SELECT
  suka_uuid5('location:' || v.state_name),
  NULL,
  'STATE'::location_level_enum,
  v.state_name,
  NULL,
  TRUE
FROM (VALUES
  ('Johor'),
  ('Kedah'),
  ('Kelantan'),
  ('Melaka'),
  ('Negeri Sembilan'),
  ('Pahang'),
  ('Perak'),
  ('Perlis'),
  ('Pulau Pinang'),
  ('Sabah'),
  ('Sarawak'),
  ('Selangor'),
  ('Terengganu'),
  ('W.P. Kuala Lumpur'),
  ('W.P. Labuan'),
  ('W.P. Putrajaya')
) AS v(state_name)
ON CONFLICT (location_id) DO UPDATE SET
  state_name = EXCLUDED.state_name,
  active     = EXCLUDED.active;

-- Districts, parented to their state
INSERT INTO location (location_id, parent_location_id, level, state_name, district_name, active)
SELECT
  suka_uuid5('location:' || v.state_name || ':' || v.district_name),
  suka_uuid5('location:' || v.state_name),
  'DISTRICT'::location_level_enum,
  v.state_name,
  v.district_name,
  TRUE
FROM (VALUES
  ('Johor', 'Batu Pahat'),
  ('Johor', 'Johor Bahru'),
  ('Johor', 'Kluang'),
  ('Johor', 'Kota Tinggi'),
  ('Johor', 'Ledang'),
  ('Johor', 'Mersing'),
  ('Johor', 'Muar'),
  ('Johor', 'Pontian'),
  ('Johor', 'Segamat'),
  ('Johor', 'Tangkak'),
  ('Kedah', 'Baling'),
  ('Kedah', 'Kota Setar'),
  ('Kedah', 'Kuala Muda'),
  ('Kedah', 'Kubang Pasu'),
  ('Kedah', 'Kulim'),
  ('Kedah', 'Langkawi'),
  ('Kedah', 'Padang Terap'),
  ('Kedah', 'Pendang'),
  ('Kedah', 'Pokok Sena'),
  ('Kedah', 'Sik'),
  ('Kedah', 'Yan'),
  ('Kelantan', 'Bachok'),
  ('Kelantan', 'Dabong'),
  ('Kelantan', 'Gua Musang'),
  ('Kelantan', 'Jeli'),
  ('Kelantan', 'Kota Bharu'),
  ('Kelantan', 'Kuala Krai'),
  ('Kelantan', 'Lojing'),
  ('Kelantan', 'Machang'),
  ('Kelantan', 'Pasir Mas'),
  ('Kelantan', 'Pasir Puteh'),
  ('Kelantan', 'Tanah Merah'),
  ('Kelantan', 'Tumpat'),
  ('Melaka', 'Alor Gajah'),
  ('Melaka', 'Jasin'),
  ('Melaka', 'Melaka Tengah'),
  ('Negeri Sembilan', 'Bahau'),
  ('Negeri Sembilan', 'Gemas'),
  ('Negeri Sembilan', 'Jelebu'),
  ('Negeri Sembilan', 'Johol'),
  ('Negeri Sembilan', 'Kuala Pilah'),
  ('Negeri Sembilan', 'Port Dickson'),
  ('Negeri Sembilan', 'Rembau'),
  ('Negeri Sembilan', 'Rompin'),
  ('Negeri Sembilan', 'Seremban'),
  ('Negeri Sembilan', 'Tampin'),
  ('Pahang', 'Bentong'),
  ('Pahang', 'Bera'),
  ('Pahang', 'Cameron Highlands'),
  ('Pahang', 'Jerantut'),
  ('Pahang', 'Kuantan'),
  ('Pahang', 'Lipis'),
  ('Pahang', 'Maran'),
  ('Pahang', 'Pekan'),
  ('Pahang', 'Raub'),
  ('Pahang', 'Rompin'),
  ('Pahang', 'Temerloh'),
  ('Perak', 'Bagan Datuk'),
  ('Perak', 'Batang Padang'),
  ('Perak', 'Gerik'),
  ('Perak', 'Hilir Perak'),
  ('Perak', 'Hulu Perak'),
  ('Perak', 'Kampar'),
  ('Perak', 'Kerian'),
  ('Perak', 'Kinta'),
  ('Perak', 'Kuala Kangsar'),
  ('Perak', 'Larut, Matang & Selama'),
  ('Perak', 'Manjung'),
  ('Perak', 'Muallim'),
  ('Perak', 'Parit Buntar'),
  ('Perak', 'Perak Tengah'),
  ('Perak', 'Tapah'),
  ('Perlis', 'Arau'),
  ('Perlis', 'Kangar'),
  ('Perlis', 'Padang Besar'),
  ('Pulau Pinang', 'Barat Daya'),
  ('Pulau Pinang', 'Seberang Perai Selatan'),
  ('Pulau Pinang', 'Seberang Perai Tengah'),
  ('Pulau Pinang', 'Seberang Perai Utara'),
  ('Pulau Pinang', 'Timur Laut'),
  ('Sabah', 'Beaufort'),
  ('Sabah', 'Kalabakan'),
  ('Sabah', 'Keningau'),
  ('Sabah', 'Kimanis'),
  ('Sabah', 'Kota Belud'),
  ('Sabah', 'Kota Kinabalu'),
  ('Sabah', 'Kota Marudu'),
  ('Sabah', 'Kuala Penyu'),
  ('Sabah', 'Kudat'),
  ('Sabah', 'Kunak'),
  ('Sabah', 'Lahad Datu'),
  ('Sabah', 'Membakut'),
  ('Sabah', 'Nabawan'),
  ('Sabah', 'Papar'),
  ('Sabah', 'Penampang'),
  ('Sabah', 'Pitas'),
  ('Sabah', 'Putatan'),
  ('Sabah', 'Ranau'),
  ('Sabah', 'Sandakan'),
  ('Sabah', 'Semporna'),
  ('Sabah', 'Sipitang'),
  ('Sabah', 'Sook'),
  ('Sabah', 'Tambunan'),
  ('Sabah', 'Tamparuli'),
  ('Sabah', 'Tawau'),
  ('Sabah', 'Tenom'),
  ('Sabah', 'Tuaran'),
  ('Sarawak', 'Balingian'),
  ('Sarawak', 'Batu Niah'),
  ('Sarawak', 'Bau'),
  ('Sarawak', 'Bekenu'),
  ('Sarawak', 'Belaga'),
  ('Sarawak', 'Betong'),
  ('Sarawak', 'Bintulu'),
  ('Sarawak', 'Dalat'),
  ('Sarawak', 'Engkelili'),
  ('Sarawak', 'Julau'),
  ('Sarawak', 'Kanowit'),
  ('Sarawak', 'Kapit'),
  ('Sarawak', 'Kota Padawan'),
  ('Sarawak', 'Kota Samarahan'),
  ('Sarawak', 'Kuching'),
  ('Sarawak', 'Lawas'),
  ('Sarawak', 'Limbang'),
  ('Sarawak', 'Lubok Antu'),
  ('Sarawak', 'Lundu'),
  ('Sarawak', 'Marudi'),
  ('Sarawak', 'Meradong'),
  ('Sarawak', 'Miri'),
  ('Sarawak', 'Mukah'),
  ('Sarawak', 'Pakan'),
  ('Sarawak', 'Saratok'),
  ('Sarawak', 'Sarikei'),
  ('Sarawak', 'Sebauh'),
  ('Sarawak', 'Selangau'),
  ('Sarawak', 'Serian'),
  ('Sarawak', 'Sibu'),
  ('Sarawak', 'Sibujaya'),
  ('Sarawak', 'Simunjan'),
  ('Sarawak', 'Song'),
  ('Sarawak', 'Sri Aman'),
  ('Sarawak', 'Tanjung Manis'),
  ('Sarawak', 'Tatau'),
  ('Selangor', 'Gombak'),
  ('Selangor', 'Hulu Langat'),
  ('Selangor', 'Hulu Selangor'),
  ('Selangor', 'Klang'),
  ('Selangor', 'Kuala Langat'),
  ('Selangor', 'Kuala Selangor'),
  ('Selangor', 'Petaling'),
  ('Selangor', 'Petaling Jaya'),
  ('Selangor', 'Rawang'),
  ('Selangor', 'Sabak Bernam'),
  ('Selangor', 'Sepang'),
  ('Terengganu', 'Besut'),
  ('Terengganu', 'Dungun'),
  ('Terengganu', 'Hulu Terengganu'),
  ('Terengganu', 'Kemaman'),
  ('Terengganu', 'Kuala Nerus'),
  ('Terengganu', 'Kuala Terengganu'),
  ('Terengganu', 'Marang'),
  ('Terengganu', 'Setiu'),
  ('W.P. Kuala Lumpur', 'Bandar Tun Razak'),
  ('W.P. Kuala Lumpur', 'Batu'),
  ('W.P. Kuala Lumpur', 'Bukit Bintang'),
  ('W.P. Kuala Lumpur', 'Cheras'),
  ('W.P. Kuala Lumpur', 'Kepong'),
  ('W.P. Kuala Lumpur', 'Lembah Pantai'),
  ('W.P. Kuala Lumpur', 'Segambut'),
  ('W.P. Kuala Lumpur', 'Seputeh'),
  ('W.P. Kuala Lumpur', 'Setiawangsa'),
  ('W.P. Kuala Lumpur', 'Titiwangsa'),
  ('W.P. Kuala Lumpur', 'Wangsa Maju'),
  ('W.P. Labuan', 'Kawasan Bandar'),
  ('W.P. Labuan', 'Kawasan Luar Bandar'),
  ('W.P. Labuan', 'W.P Labuan'),
  ('W.P. Putrajaya', 'Cyberjaya'),
  ('W.P. Putrajaya', 'Wp Putrajaya')
) AS v(state_name, district_name)
ON CONFLICT (location_id) DO UPDATE SET
  parent_location_id = EXCLUDED.parent_location_id,
  state_name         = EXCLUDED.state_name,
  district_name      = EXCLUDED.district_name,
  active             = EXCLUDED.active;

COMMIT;
