-- =========================================================
-- 10_wwf_catalogue_54.sql   ** GENERATED FILE — DO NOT EDIT **
-- =========================================================
-- Regenerate with:  cd backend && python scripts/generate_wwf_catalogue_54.py
-- Source: data/wwf_fish_context_55_words_max_with_short_descriptions.csv
-- 54 WWF-listed fishes. SF013 Demuduk is inactive and is not listed here.

BEGIN;

INSERT INTO seafood_item (
  seafood_item_id, code, canonical_name_ms, display_name_en,
  scientific_name, scientific_name_normalized, taxonomic_level, family,
  fish_type, description, supports_cv, active, notes, primary_image_url
)
SELECT
  suka_uuid5('seafood_item:' || v.code),
  v.code, v.canonical_name_ms, v.display_name_en,
  v.scientific_name, lower(trim(v.scientific_name)), v.taxonomic_level, v.family,
  v.fish_type, v.description, v.supports_cv, TRUE, v.notes, v.primary_image_url
FROM (VALUES
  ('SF016', 'Alaskan Pollock', 'Alaskan Pollock', 'Gadus chalcogrammus', 'species', 'Gadidae', 'marine pelagic', 'A cold-water schooling whitefish that forms an important commercial fishery in the North Pacific.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF016.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF017', 'Albacore Tuna', 'Albacore Tuna', 'Thunnus alalunga', 'species', 'Scombridae', 'marine pelagic', 'A highly migratory tuna with firm, pale meat, commonly found in temperate and tropical open-ocean waters.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF017.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF018', 'Atlantic Bluefin Tuna', 'Atlantic Bluefin Tuna', 'Thunnus thynnus', 'species', 'Scombridae', 'marine pelagic', 'A large, fast-swimming tuna that migrates across the open Atlantic and is highly valued in premium seafood markets.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF018.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF019', 'Atlantic Cod', 'Atlantic Cod', 'Gadus Morhua', 'species', 'Gadidae', 'marine demersal', 'A cold-water cod species associated with northern Atlantic waters and valued for its mild, flaky flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF019.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF020', 'Atlantic Salmon', 'Atlantic Salmon', 'Salmo salar', 'species', 'Salmonidae', 'marine', 'A widely farmed salmon with pink-orange flesh, raised in marine cages and commonly sold fresh or smoked.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF020.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF021', 'Bakulan', 'Skipjack', 'Katsuwonus pelamis', 'species', 'Scombridae', 'marine pelagic', 'A small tropical tuna that travels in schools through warm ocean waters and is widely used in Southeast Asian fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF021.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF022', 'Bawal Emas', 'Snubnose Pompano', 'Trachinotus blochii', 'species', 'Carangidae', 'marine', 'A warm-water pompano with a streamlined body, often associated with coastal waters and marine aquaculture.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF022.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF002', 'Bawal Hitam', 'Black Pomfret', 'Parastromateus niger', 'species', 'Carangidae', 'marine demersal', 'A deep-bodied pomfret with a distinctive dark body, commonly sold in Malaysian seafood markets.', TRUE, 'https://sukaseafood-654b7.web.app/catalogue/SF002.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF006', 'Bawal Putih', 'Chinese Silver Pomfret', 'Pampus chinensis', 'species', 'Stromateidae', 'marine demersal', 'A silver-bodied pomfret found over muddy coastal seabeds and widely consumed across Asian markets.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF006.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF023', 'Belanak', 'Longfin Grey Mullet', 'Valamugil cunnesius', 'species', 'Mugilidae', 'marine-estuarine', 'A coastal mullet associated with estuaries and shallow waters, recognised for its elongated body and fine-textured flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF023.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF024', 'Bulu Ayam (Ikan Masin)', 'Grenadler Anchovy', 'Coilia spp.', 'genus', 'Engraulidae', 'marine pelagic', 'A small anchovy-like fish used locally as dried or salted seafood and associated with Malaysian coastal fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF024.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF025', 'Bulus', 'Silver Sillago', 'Sillago sihama', 'species', 'Sillaginidae', 'marine demersal', 'A small silver fish that lives over sandy and muddy coastal bottoms and is commonly caught in nearshore fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF025.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF007', 'Cencaru', 'Hardtail Scad', 'Megalaspis cordyla', 'species', 'Carangidae', 'marine pelagic', 'A robust coastal scad that forms schools in tropical waters and is a familiar fish in Malaysian markets.', TRUE, 'https://sukaseafood-654b7.web.app/catalogue/SF007.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF026', 'Chinook Salmon', 'Chinook Salmon', 'Oncorhynchus tshawytscha', 'species', 'Salmonidae', 'anadromous', 'A large Pacific salmon known for its rich flavour and dark flesh, migrating between the ocean and freshwater rivers.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF026.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF027', 'Hoki', 'Hoki', 'Macruronus novaezelandiae', 'species', 'Merlucciidae', 'marine demersal', 'A long-bodied cold-water fish commonly caught around New Zealand and used widely as a white-fleshed seafood.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF027.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF028', 'Ikan Bilis', 'Anchovies', 'Stolephorus spp.', 'genus', 'Engraulidae', 'marine pelagic', 'Small schooling anchovies widely used fresh, dried or fermented in Malaysian cuisine and coastal food traditions.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF028.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF029', 'Ikan Delah / Tauhu', 'Yellowtail Fusiler', 'Caesio cuning', 'species', 'Caesionidae', 'marine reef', 'A colourful fusilier that forms schools around reefs and coastal waters, often encountered in tropical Southeast Asian fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF029.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF030', 'Ikan Gelama', 'Croakers', 'Sciaenidae spp.', 'family', 'Sciaenidae', 'marine demersal', 'A group of coastal croakers that often live near muddy bottoms and estuaries and produce characteristic drumming sounds.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF030.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF003', 'Ikan Merah', 'Red Snapper', 'Lutjanus sebae', 'species', 'Lutjanidae', 'marine reef', 'A red snapper associated with reefs and coastal waters, known for firm flesh and a bright reddish body.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF003.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF031', 'Ikan Sebelah', 'Flounder', 'Pseudorhombus malayanus', 'species', 'Paralichthyidae', 'marine demersal', 'A bottom-dwelling flatfish with both eyes on one side of its body, living mainly over sandy or muddy seabeds.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF031.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF032', 'Ikan Selar', 'Common Scad', 'Decapterus akaadsi', 'species', 'Carangidae', 'marine pelagic', 'A small schooling scad common in tropical waters and a familiar fish in Malaysian seafood markets.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF032.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF008', 'Jenahak', 'John''s Snapper', 'Lutjanus johnii', 'species', 'Lutjanidae', 'marine reef', 'A snapper associated with coastal and reef habitats, recognised for its coppery-red body and firm flesh.', TRUE, 'https://sukaseafood-654b7.web.app/catalogue/SF008.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF033', 'Jerung / Yu', 'All Sharks', 'Elasmobranchii', 'class', 'Elasmobranchii', 'marine cartilaginous', 'A broad group of sharks that occupy many marine habitats and play important roles as ocean predators.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF033.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF034', 'Kekacang', 'Pickhandle Barracuda', 'Sphyraena jello', 'species', 'Sphyraenidae', 'marine pelagic', 'A fast predatory barracuda found in tropical coastal waters, recognisable by its elongated body and strong jaws.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF034.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF001', 'Kembung / Pelaling', 'Indian Mackerel', 'Rastrelliger kanagurta', 'species', 'Scombridae', 'marine pelagic', 'A small schooling mackerel widely eaten in Malaysia, with oily flesh and a strong place in everyday local cuisine.', TRUE, 'https://sukaseafood-654b7.web.app/catalogue/SF001.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF035', 'Kerapu Bebeh', 'Sixbar Grouper', 'Epinephelus sexfasciatus', 'species', 'Serranidae', 'marine reef', 'A small grouper associated with reef and rocky coastal habitats and valued for its firm, white flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF035.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF005', 'Kerapu Bintik', 'Orange Spotted Grouper', 'Epinephelus coioides', 'species', 'Serranidae', 'marine reef', 'A reef-associated grouper found in tropical coastal waters, commonly sold as a premium food fish in Southeast Asia.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF005.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF036', 'Kerapu Ekor Gelap', 'Duskytail Grouper', 'Epinephelus bleekeri', 'species', 'Serranidae', 'marine reef', 'A grouper associated with tropical coastal habitats, with a sturdy body and firm, white flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF036.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF037', 'Kerapu Harimau', 'Brown-marble Grouper', 'Epinephelus fuscoguttatus', 'species', 'Serranidae', 'marine reef', 'A large, reef-associated grouper with a marbled pattern, commonly produced through marine cage aquaculture.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF037.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF038', 'Kerapu Kertang', 'Giant Grouper', 'Epinephelus lanceolatus', 'species', 'Serranidae', 'marine reef', 'A very large grouper that can inhabit reefs and coastal waters, reaching exceptional size compared with many groupers.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF038.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF039', 'Kerapu Lumpur', 'Malabar Grouper', 'Epinephelus malabaricus', 'species', 'Serranidae', 'marine reef', 'A large tropical grouper associated with coastal and reef habitats and known for its firm, white flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF039.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF040', 'Kerapu Sunoh / Kerapu Bara', 'Coral Trout / Leopard Coral Grouper', 'Plectropomus spp.', 'genus', 'Serranidae', 'marine reef', 'A brightly coloured reef grouper associated with coral habitats and highly valued in Southeast Asian seafood markets.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF040.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF041', 'Kerapu Tikus', 'Humpback Grouper', 'Cromileptes altivelis', 'species', 'Serranidae', 'marine reef', 'A distinctive grouper with a rounded profile, associated with reef habitats and increasingly encountered in aquaculture.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF041.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF042', 'Kerepoh', 'Bigeye Trevally', 'Caranx sexfasciatus', 'species', 'Carangidae', 'marine pelagic', 'A large trevally with a powerful build, commonly found around coastal reefs and deeper tropical waters.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF042.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF009', 'Kerisi', 'Treadfin Breams', 'Nemipterus japonicus', 'species', 'Nemipteridae', 'marine demersal', 'A small to medium coastal bream found over sandy or muddy bottoms and widely represented in Asian fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF009.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF043', 'Kikek', 'Ponyfish', 'Leiognathus spp.', 'genus', 'Leiognathidae', 'marine demersal', 'Small schooling ponyfish associated with coastal waters and sandy or muddy seabeds.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF043.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF044', 'Kunyit-kunyit', 'Brownstripe Red Snapper', 'Lutjanus vitta', 'species', 'Lutjanidae', 'marine reef', 'A small red snapper associated with tropical coastal habitats and commonly caught by bottom-oriented fishing gears.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF044.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF045', 'Kurau', 'Striped Threadfin', 'Polydactylus plebeius', 'species', 'Polynemidae', 'marine-estuarine', 'A long-bodied threadfin that lives in coastal and estuarine waters and is valued for its firm flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF045.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF046', 'Mameng', 'Humphead Wrasse', 'Cheilinus undulatus', 'species', 'Labridae', 'marine reef', 'A large, slow-growing wrasse closely associated with coral reefs and recognisable by its thick lips and hump-shaped head.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF046.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF047', 'Mata Besar / Lolong', 'Bigeye Scad', 'Selar crumenophthalmus', 'species', 'Carangidae', 'marine pelagic', 'A schooling scad found in coastal and offshore waters and commonly landed in tropical Southeast Asian fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF047.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF048', 'Parang', 'Dorab Wolf-herring', 'Chirocentrus dorab', 'species', 'Chirocentridae', 'marine pelagic', 'A long, slender marine predator with a streamlined body, often found in tropical coastal and open-water habitats.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF048.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF049', 'Pari', 'All Rays', 'Chondrichthyes', 'class', 'Chondrichthyes', 'marine cartilaginous', 'A broad group of rays with flattened bodies and wing-like fins, found across many marine habitats.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF049.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF050', 'Patin', 'Pangasius', 'Pangasius bocourti', 'species', 'Pangasiidae', 'freshwater', 'A freshwater catfish farmed widely in Southeast Asia, valued for its mild flavour and soft, white flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF050.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF010', 'Pelata', 'Blackfin Scad', 'Alepes melanoptera', 'species', 'Carangidae', 'marine pelagic', 'A small tropical scad that forms schools in coastal waters and is commonly caught by purse seine fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF010.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF011', 'Selar Kuning', 'Yellowtail Scad', 'Selaroides leptolepis', 'species', 'Carangidae', 'marine pelagic', 'A small yellow-tailed scad associated with tropical coastal waters and commonly caught in nearshore fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF011.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF051', 'Siakap Merah', 'Mangrove Red Snapper', 'Lutjanus argentimaculatus', 'species', 'Lutjanidae', 'marine-estuarine', 'A mangrove-associated snapper that can live in estuaries and coastal waters and is valued as a food fish.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF051.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF014', 'Siakap Putih', 'Asian seabass / Barramundi', 'Lates calcarifer', 'species', 'Latidae', 'marine-estuarine', 'A versatile Asian seabass found in estuaries, coastal waters and farms, known for its mild flavour and firm flesh.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF014.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF052', 'Tamban / Sardin', 'Sardine', 'Spratelloides gracilis', 'species', 'Clupeidae', 'marine pelagic', 'A small schooling sardine associated with warm coastal waters and widely used as a food fish in Southeast Asia.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF052.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF012', 'Tenggiri', 'Narrow-barred Spanish Mackerel', 'Scomberomorus commerson', 'species', 'Scombridae', 'marine pelagic', 'A large, fast-swimming mackerel with firm flesh, widely consumed in Malaysia and other tropical Asian markets.', TRUE, 'https://sukaseafood-654b7.web.app/catalogue/SF012.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF053', 'Terubok', 'Longtail Shad', 'Tenualosa macrura', 'species', 'Dorosomatidae', 'anadromous', 'A long-bodied shad associated with coastal waters and river-influenced habitats, important in regional fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF053.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF004', 'Tilapia', 'Tilapia', 'Oreochromis Niloticus', 'species', 'Cichlidae', 'freshwater', 'A hardy freshwater tilapia commonly farmed for its mild flavour, firm flesh and adaptable production conditions.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF004.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF015', 'Tongkol', 'Longtail Tuna', 'Thunnus tonggol', 'species', 'Scombridae', 'marine pelagic', 'A tropical tuna that lives in coastal and offshore waters and is widely used in Southeast Asian fisheries.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF015.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF054', 'Tongkol Kurik', 'Eastern Little Tuna', 'Euthynnus affinis', 'species', 'Scombridae', 'marine pelagic', 'A small tropical tuna with firm flesh, commonly found in warm coastal and offshore waters.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF054.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.'),
  ('SF055', 'Tongkol Selasih', 'Frigate Tuna', 'Auxis thazard', 'species', 'Scombridae', 'marine pelagic', 'A small tuna species found in warm ocean waters, recognised by its compact body and strong swimming ability.', FALSE, 'https://sukaseafood-654b7.web.app/catalogue/SF055.jpg', 'WWF Save Our Seafood listing. Ratings stay on retrieved catch-method rows only.')
) AS v(code, canonical_name_ms, display_name_en, scientific_name,
       taxonomic_level, family, fish_type, description, supports_cv,
       primary_image_url, notes)
ON CONFLICT (seafood_item_id) DO UPDATE SET
  code                       = EXCLUDED.code,
  canonical_name_ms          = EXCLUDED.canonical_name_ms,
  display_name_en            = EXCLUDED.display_name_en,
  scientific_name            = EXCLUDED.scientific_name,
  scientific_name_normalized = EXCLUDED.scientific_name_normalized,
  taxonomic_level            = EXCLUDED.taxonomic_level,
  family                     = EXCLUDED.family,
  fish_type                  = EXCLUDED.fish_type,
  description                = EXCLUDED.description,
  supports_cv                = EXCLUDED.supports_cv,
  active                     = EXCLUDED.active,
  notes                      = EXCLUDED.notes,
  primary_image_url          = EXCLUDED.primary_image_url,
  updated_at                 = now();

INSERT INTO seafood_alias (
  seafood_alias_id, seafood_item_id, alias_name, language_code, alias_type, verified
)
SELECT
  suka_uuid5('seafood_alias:' || v.code || ':' || lower(trim(v.alias_name))),
  suka_uuid5('seafood_item:' || v.code),
  v.alias_name, v.language_code, v.alias_type::seafood_alias_type_enum, TRUE
FROM (VALUES
  ('SF016', 'Alaskan Pollock', 'ms', 'MALAY'),
  ('SF016', 'Ikan Alaskan Pollock', 'ms', 'MALAY'),
  ('SF016', 'Gadus chalcogrammus', 'la', 'SCIENTIFIC'),
  ('SF017', 'Albacore Tuna', 'ms', 'MALAY'),
  ('SF017', 'Ikan Albacore Tuna', 'ms', 'MALAY'),
  ('SF017', 'Thunnus alalunga', 'la', 'SCIENTIFIC'),
  ('SF018', 'Atlantic Bluefin Tuna', 'ms', 'MALAY'),
  ('SF018', 'Ikan Atlantic Bluefin Tuna', 'ms', 'MALAY'),
  ('SF018', 'Thunnus thynnus', 'la', 'SCIENTIFIC'),
  ('SF019', 'Atlantic Cod', 'ms', 'MALAY'),
  ('SF019', 'Ikan Atlantic Cod', 'ms', 'MALAY'),
  ('SF019', 'Gadus Morhua', 'la', 'SCIENTIFIC'),
  ('SF020', 'Atlantic Salmon', 'ms', 'MALAY'),
  ('SF020', 'Ikan Atlantic Salmon', 'ms', 'MALAY'),
  ('SF020', 'Salmo salar', 'la', 'SCIENTIFIC'),
  ('SF021', 'Bakulan', 'ms', 'MALAY'),
  ('SF021', 'Ikan Bakulan', 'ms', 'MALAY'),
  ('SF021', 'Skipjack', 'en', 'ENGLISH_COMMON'),
  ('SF021', 'Katsuwonus pelamis', 'la', 'SCIENTIFIC'),
  ('SF022', 'Bawal Emas', 'ms', 'MALAY'),
  ('SF022', 'Ikan Bawal Emas', 'ms', 'MALAY'),
  ('SF022', 'Snubnose Pompano', 'en', 'ENGLISH_COMMON'),
  ('SF022', 'Trachinotus blochii', 'la', 'SCIENTIFIC'),
  ('SF002', 'Bawal Hitam', 'ms', 'MALAY'),
  ('SF002', 'Ikan Bawal Hitam', 'ms', 'MALAY'),
  ('SF002', 'Black Pomfret', 'en', 'ENGLISH_COMMON'),
  ('SF002', 'Parastromateus niger', 'la', 'SCIENTIFIC'),
  ('SF006', 'Bawal Putih', 'ms', 'MALAY'),
  ('SF006', 'Ikan Bawal Putih', 'ms', 'MALAY'),
  ('SF006', 'Chinese Silver Pomfret', 'en', 'ENGLISH_COMMON'),
  ('SF006', 'Pampus chinensis', 'la', 'SCIENTIFIC'),
  ('SF023', 'Belanak', 'ms', 'MALAY'),
  ('SF023', 'Ikan Belanak', 'ms', 'MALAY'),
  ('SF023', 'Longfin Grey Mullet', 'en', 'ENGLISH_COMMON'),
  ('SF023', 'Valamugil cunnesius', 'la', 'SCIENTIFIC'),
  ('SF024', 'Bulu Ayam (Ikan Masin)', 'ms', 'MALAY'),
  ('SF024', 'Ikan Bulu Ayam (Ikan Masin)', 'ms', 'MALAY'),
  ('SF024', 'Grenadler Anchovy', 'en', 'ENGLISH_COMMON'),
  ('SF024', 'Coilia spp.', 'la', 'SCIENTIFIC'),
  ('SF025', 'Bulus', 'ms', 'MALAY'),
  ('SF025', 'Ikan Bulus', 'ms', 'MALAY'),
  ('SF025', 'Silver Sillago', 'en', 'ENGLISH_COMMON'),
  ('SF025', 'Sillago sihama', 'la', 'SCIENTIFIC'),
  ('SF007', 'Cencaru', 'ms', 'MALAY'),
  ('SF007', 'Ikan Cencaru', 'ms', 'MALAY'),
  ('SF007', 'Hardtail Scad', 'en', 'ENGLISH_COMMON'),
  ('SF007', 'Megalaspis cordyla', 'la', 'SCIENTIFIC'),
  ('SF026', 'Chinook Salmon', 'ms', 'MALAY'),
  ('SF026', 'Ikan Chinook Salmon', 'ms', 'MALAY'),
  ('SF026', 'Oncorhynchus tshawytscha', 'la', 'SCIENTIFIC'),
  ('SF027', 'Hoki', 'ms', 'MALAY'),
  ('SF027', 'Ikan Hoki', 'ms', 'MALAY'),
  ('SF027', 'Macruronus novaezelandiae', 'la', 'SCIENTIFIC'),
  ('SF028', 'Ikan Bilis', 'ms', 'MALAY'),
  ('SF028', 'Anchovies', 'en', 'ENGLISH_COMMON'),
  ('SF028', 'Stolephorus spp.', 'la', 'SCIENTIFIC'),
  ('SF029', 'Ikan Delah / Tauhu', 'ms', 'MALAY'),
  ('SF029', 'Ikan Delah', 'ms', 'MALAY'),
  ('SF029', 'Tauhu', 'ms', 'MALAY'),
  ('SF029', 'Yellowtail Fusiler', 'en', 'ENGLISH_COMMON'),
  ('SF029', 'Caesio cuning', 'la', 'SCIENTIFIC'),
  ('SF030', 'Ikan Gelama', 'ms', 'MALAY'),
  ('SF030', 'Croakers', 'en', 'ENGLISH_COMMON'),
  ('SF030', 'Sciaenidae spp.', 'la', 'SCIENTIFIC'),
  ('SF003', 'Ikan Merah', 'ms', 'MALAY'),
  ('SF003', 'Red Snapper', 'en', 'ENGLISH_COMMON'),
  ('SF003', 'Lutjanus sebae', 'la', 'SCIENTIFIC'),
  ('SF031', 'Ikan Sebelah', 'ms', 'MALAY'),
  ('SF031', 'Flounder', 'en', 'ENGLISH_COMMON'),
  ('SF031', 'Pseudorhombus malayanus', 'la', 'SCIENTIFIC'),
  ('SF032', 'Ikan Selar', 'ms', 'MALAY'),
  ('SF032', 'Common Scad', 'en', 'ENGLISH_COMMON'),
  ('SF032', 'Decapterus akaadsi', 'la', 'SCIENTIFIC'),
  ('SF008', 'Jenahak', 'ms', 'MALAY'),
  ('SF008', 'Ikan Jenahak', 'ms', 'MALAY'),
  ('SF008', 'John''s Snapper', 'en', 'ENGLISH_COMMON'),
  ('SF008', 'Lutjanus johnii', 'la', 'SCIENTIFIC'),
  ('SF033', 'Jerung / Yu', 'ms', 'MALAY'),
  ('SF033', 'Jerung', 'ms', 'MALAY'),
  ('SF033', 'Yu', 'ms', 'MALAY'),
  ('SF033', 'Ikan Jerung', 'ms', 'MALAY'),
  ('SF033', 'All Sharks', 'en', 'ENGLISH_COMMON'),
  ('SF033', 'Elasmobranchii', 'la', 'SCIENTIFIC'),
  ('SF034', 'Kekacang', 'ms', 'MALAY'),
  ('SF034', 'Ikan Kekacang', 'ms', 'MALAY'),
  ('SF034', 'Pickhandle Barracuda', 'en', 'ENGLISH_COMMON'),
  ('SF034', 'Sphyraena jello', 'la', 'SCIENTIFIC'),
  ('SF001', 'Kembung / Pelaling', 'ms', 'MALAY'),
  ('SF001', 'Kembung', 'ms', 'MALAY'),
  ('SF001', 'Pelaling', 'ms', 'MALAY'),
  ('SF001', 'Ikan Kembung', 'ms', 'MALAY'),
  ('SF001', 'Indian Mackerel', 'en', 'ENGLISH_COMMON'),
  ('SF001', 'Rastrelliger kanagurta', 'la', 'SCIENTIFIC'),
  ('SF035', 'Kerapu Bebeh', 'ms', 'MALAY'),
  ('SF035', 'Ikan Kerapu Bebeh', 'ms', 'MALAY'),
  ('SF035', 'Sixbar Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF035', 'Epinephelus sexfasciatus', 'la', 'SCIENTIFIC'),
  ('SF005', 'Kerapu Bintik', 'ms', 'MALAY'),
  ('SF005', 'Ikan Kerapu Bintik', 'ms', 'MALAY'),
  ('SF005', 'Orange Spotted Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF005', 'Epinephelus coioides', 'la', 'SCIENTIFIC'),
  ('SF036', 'Kerapu Ekor Gelap', 'ms', 'MALAY'),
  ('SF036', 'Ikan Kerapu Ekor Gelap', 'ms', 'MALAY'),
  ('SF036', 'Duskytail Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF036', 'Epinephelus bleekeri', 'la', 'SCIENTIFIC'),
  ('SF037', 'Kerapu Harimau', 'ms', 'MALAY'),
  ('SF037', 'Ikan Kerapu Harimau', 'ms', 'MALAY'),
  ('SF037', 'Brown-marble Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF037', 'Epinephelus fuscoguttatus', 'la', 'SCIENTIFIC'),
  ('SF038', 'Kerapu Kertang', 'ms', 'MALAY'),
  ('SF038', 'Ikan Kerapu Kertang', 'ms', 'MALAY'),
  ('SF038', 'Giant Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF038', 'Epinephelus lanceolatus', 'la', 'SCIENTIFIC'),
  ('SF039', 'Kerapu Lumpur', 'ms', 'MALAY'),
  ('SF039', 'Ikan Kerapu Lumpur', 'ms', 'MALAY'),
  ('SF039', 'Malabar Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF039', 'Epinephelus malabaricus', 'la', 'SCIENTIFIC'),
  ('SF040', 'Kerapu Sunoh / Kerapu Bara', 'ms', 'MALAY'),
  ('SF040', 'Kerapu Sunoh', 'ms', 'MALAY'),
  ('SF040', 'Kerapu Bara', 'ms', 'MALAY'),
  ('SF040', 'Ikan Kerapu Sunoh', 'ms', 'MALAY'),
  ('SF040', 'Coral Trout', 'en', 'ENGLISH_COMMON'),
  ('SF040', 'Leopard Coral Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF040', 'Plectropomus spp.', 'la', 'SCIENTIFIC'),
  ('SF041', 'Kerapu Tikus', 'ms', 'MALAY'),
  ('SF041', 'Ikan Kerapu Tikus', 'ms', 'MALAY'),
  ('SF041', 'Humpback Grouper', 'en', 'ENGLISH_COMMON'),
  ('SF041', 'Cromileptes altivelis', 'la', 'SCIENTIFIC'),
  ('SF042', 'Kerepoh', 'ms', 'MALAY'),
  ('SF042', 'Ikan Kerepoh', 'ms', 'MALAY'),
  ('SF042', 'Bigeye Trevally', 'en', 'ENGLISH_COMMON'),
  ('SF042', 'Caranx sexfasciatus', 'la', 'SCIENTIFIC'),
  ('SF009', 'Kerisi', 'ms', 'MALAY'),
  ('SF009', 'Ikan Kerisi', 'ms', 'MALAY'),
  ('SF009', 'Treadfin Breams', 'en', 'ENGLISH_COMMON'),
  ('SF009', 'Nemipterus japiconus', 'la', 'SCIENTIFIC'),
  ('SF043', 'Kikek', 'ms', 'MALAY'),
  ('SF043', 'Ikan Kikek', 'ms', 'MALAY'),
  ('SF043', 'Ponyfish', 'en', 'ENGLISH_COMMON'),
  ('SF043', 'Leiognathus spp.', 'la', 'SCIENTIFIC'),
  ('SF044', 'Kunyit-kunyit', 'ms', 'MALAY'),
  ('SF044', 'Ikan Kunyit-kunyit', 'ms', 'MALAY'),
  ('SF044', 'Brownstripe Red Snapper', 'en', 'ENGLISH_COMMON'),
  ('SF044', 'Lutjanus vitta', 'la', 'SCIENTIFIC'),
  ('SF045', 'Kurau', 'ms', 'MALAY'),
  ('SF045', 'Ikan Kurau', 'ms', 'MALAY'),
  ('SF045', 'Striped Threadfin', 'en', 'ENGLISH_COMMON'),
  ('SF045', 'Polydactylus plebeius', 'la', 'SCIENTIFIC'),
  ('SF046', 'Mameng', 'ms', 'MALAY'),
  ('SF046', 'Ikan Mameng', 'ms', 'MALAY'),
  ('SF046', 'Humphead Wrasse', 'en', 'ENGLISH_COMMON'),
  ('SF046', 'Cheilinus undulatus', 'la', 'SCIENTIFIC'),
  ('SF047', 'Mata Besar / Lolong', 'ms', 'MALAY'),
  ('SF047', 'Mata Besar', 'ms', 'MALAY'),
  ('SF047', 'Lolong', 'ms', 'MALAY'),
  ('SF047', 'Ikan Mata Besar', 'ms', 'MALAY'),
  ('SF047', 'Bigeye Scad', 'en', 'ENGLISH_COMMON'),
  ('SF047', 'Selar crumenophthalmus', 'la', 'SCIENTIFIC'),
  ('SF048', 'Parang', 'ms', 'MALAY'),
  ('SF048', 'Ikan Parang', 'ms', 'MALAY'),
  ('SF048', 'Dorab Wolf-herring', 'en', 'ENGLISH_COMMON'),
  ('SF048', 'Chirocentrus dorab', 'la', 'SCIENTIFIC'),
  ('SF049', 'Pari', 'ms', 'MALAY'),
  ('SF049', 'Ikan Pari', 'ms', 'MALAY'),
  ('SF049', 'All Rays', 'en', 'ENGLISH_COMMON'),
  ('SF049', 'Chondrichthyes', 'la', 'SCIENTIFIC'),
  ('SF050', 'Patin', 'ms', 'MALAY'),
  ('SF050', 'Ikan Patin', 'ms', 'MALAY'),
  ('SF050', 'Pangasius', 'en', 'ENGLISH_COMMON'),
  ('SF050', 'Pangasius bocourti', 'la', 'SCIENTIFIC'),
  ('SF010', 'Pelata', 'ms', 'MALAY'),
  ('SF010', 'Ikan Pelata', 'ms', 'MALAY'),
  ('SF010', 'Blackfin Scad', 'en', 'ENGLISH_COMMON'),
  ('SF010', 'Alepes melanoptera', 'la', 'SCIENTIFIC'),
  ('SF011', 'Selar Kuning', 'ms', 'MALAY'),
  ('SF011', 'Ikan Selar Kuning', 'ms', 'MALAY'),
  ('SF011', 'Yellowtail Scad', 'en', 'ENGLISH_COMMON'),
  ('SF011', 'Selaroides leptolepis', 'la', 'SCIENTIFIC'),
  ('SF051', 'Siakap Merah', 'ms', 'MALAY'),
  ('SF051', 'Ikan Siakap Merah', 'ms', 'MALAY'),
  ('SF051', 'Mangrove Red Snapper', 'en', 'ENGLISH_COMMON'),
  ('SF051', 'Lutjanus argentimaculatus', 'la', 'SCIENTIFIC'),
  ('SF014', 'Siakap Putih', 'ms', 'MALAY'),
  ('SF014', 'Ikan Siakap Putih', 'ms', 'MALAY'),
  ('SF014', 'Asian seabass', 'en', 'ENGLISH_COMMON'),
  ('SF014', 'Barramundi', 'en', 'ENGLISH_COMMON'),
  ('SF014', 'Lates calcarifer', 'la', 'SCIENTIFIC'),
  ('SF052', 'Tamban / Sardin', 'ms', 'MALAY'),
  ('SF052', 'Tamban', 'ms', 'MALAY'),
  ('SF052', 'Sardin', 'ms', 'MALAY'),
  ('SF052', 'Ikan Tamban', 'ms', 'MALAY'),
  ('SF052', 'Sardine', 'en', 'ENGLISH_COMMON'),
  ('SF052', 'Spratelloides gracilis', 'la', 'SCIENTIFIC'),
  ('SF012', 'Tenggiri', 'ms', 'MALAY'),
  ('SF012', 'Ikan Tenggiri', 'ms', 'MALAY'),
  ('SF012', 'Narrow-barred Spanish Mackerel', 'en', 'ENGLISH_COMMON'),
  ('SF012', 'Scomberomorus commerson', 'la', 'SCIENTIFIC'),
  ('SF053', 'Terubok', 'ms', 'MALAY'),
  ('SF053', 'Ikan Terubok', 'ms', 'MALAY'),
  ('SF053', 'Longtail Shad', 'en', 'ENGLISH_COMMON'),
  ('SF053', 'Tenualosa macrura', 'la', 'SCIENTIFIC'),
  ('SF004', 'Tilapia', 'ms', 'MALAY'),
  ('SF004', 'Ikan Tilapia', 'ms', 'MALAY'),
  ('SF004', 'Oreochromis Niloticus', 'la', 'SCIENTIFIC'),
  ('SF015', 'Tongkol', 'ms', 'MALAY'),
  ('SF015', 'Ikan Tongkol', 'ms', 'MALAY'),
  ('SF015', 'Longtail Tuna', 'en', 'ENGLISH_COMMON'),
  ('SF015', 'Thunnus tonggol', 'la', 'SCIENTIFIC'),
  ('SF054', 'Tongkol Kurik', 'ms', 'MALAY'),
  ('SF054', 'Ikan Tongkol Kurik', 'ms', 'MALAY'),
  ('SF054', 'Eastern Little Tuna', 'en', 'ENGLISH_COMMON'),
  ('SF054', 'Euthynnus affinis', 'la', 'SCIENTIFIC'),
  ('SF055', 'Tongkol Selasih', 'ms', 'MALAY'),
  ('SF055', 'Ikan Tongkol Selasih', 'ms', 'MALAY'),
  ('SF055', 'Frigate Tuna', 'en', 'ENGLISH_COMMON'),
  ('SF055', 'Auxis thazard', 'la', 'SCIENTIFIC')
) AS v(code, alias_name, language_code, alias_type)
WHERE NOT EXISTS (
  SELECT 1
  FROM seafood_alias existing
  WHERE existing.seafood_item_id = suka_uuid5('seafood_item:' || v.code)
    AND lower(trim(existing.alias_name)) = lower(trim(v.alias_name))
);

COMMIT;
