-- =========================================================
-- 11_wwf_sos_2022.sql   ** GENERATED FILE — DO NOT EDIT **
-- =========================================================
-- Regenerate with:  cd backend && python scripts/generate_wwf_catalogue_54.py
-- Source: data/wwf_fish_context_55_words_max_with_short_descriptions.csv

BEGIN;

INSERT INTO source_snapshot (
  source_snapshot_id, data_source_id, version_label,
  source_period_start, source_period_end, retrieved_at, collection_method, manifest, notes
)
SELECT
  suka_uuid5('source_snapshot:wwf_sos:wwf-sos-2022-54-context'),
  suka_uuid5('data_source:wwf_sos'),
  'wwf-sos-2022-54-context',
  '2022-01-01'::date,
  '2022-12-31'::date,
  '2026-09-14T00:00:00+08:00'::timestamptz,
  'MANUAL_PDF_TRANSCRIPTION'::collection_method_enum,
  '{"files": ["wwf_fish_context_55_words_max_with_short_descriptions.csv"]}'::jsonb,
  'WWF Save Our Seafood listings with retrieved 55-word context copy.'
ON CONFLICT (source_snapshot_id) DO UPDATE SET
  retrieved_at = EXCLUDED.retrieved_at,
  manifest     = EXCLUDED.manifest,
  notes        = EXCLUDED.notes;

INSERT INTO wwf_assessment (
  wwf_assessment_id, seafood_item_id, source_snapshot_id, source_record_key,
  common_name_raw, secondary_common_name_raw, scientific_name_raw, rating,
  origin_raw, origin_code, production_type, production_method_raw,
  production_method_code, certification_raw, context, notes_raw
)
SELECT
  suka_uuid5('wwf_assessment:wwf-sos-2022-54-context:' || v.source_record_key),
  suka_uuid5('seafood_item:' || v.code),
  suka_uuid5('source_snapshot:wwf_sos:wwf-sos-2022-54-context'),
  v.source_record_key,
  v.common_name_raw, v.secondary_common_name_raw, v.scientific_name_raw,
  v.rating::sustainability_rating_enum,
  v.origin_raw, v.origin_code, v.production_type, v.production_method_raw,
  v.production_method_code, v.certification_raw, v.context, v.notes_raw
FROM (VALUES
  ('SF016', 'wwf-row-6', 'Alaskan Pollock', NULL, 'Gadus chalcogrammus', 'REDUCE', 'USA', 'US', 'WILD', 'Bottom trawl (Wild caught)', 'TRAWL', NULL, 'WWF notes Alaska pollock shares waters with protected species such as Steller sea lions, Chinook salmon and sharks. Bycatch is relatively low, but bottom trawling can affect sponge beds and sedimentary habitat. These ecosystem and habitat concerns support a Reduce rating.', 'A cold-water schooling whitefish that forms an important commercial fishery in the North Pacific.'),
  ('SF017', 'wwf-row-7', 'Albacore Tuna', NULL, 'Thunnus alalunga', 'BEST_CHOICE', 'South Africa', 'ZA', 'WILD', 'Pole and line (Wild caught)', 'HOOK_AND_LINE', NULL, 'WWF notes Albacore Tuna is highly migratory and Near Threatened. The cited southern-stock assessment no longer considered the stock overfished or undergoing overfishing, while South African pole-and-line fishing is comparatively selective. These factors support the Best Choice rating for this record.', 'A highly migratory tuna with firm, pale meat, commonly found in temperate and tropical open-ocean waters.'),
  ('SF018', 'wwf-row-8', 'Atlantic Bluefin Tuna', NULL, 'Thunnus thynnus', 'AVOID', 'Atlantic Ocean', NULL, 'WILD', 'Pelagic longlines (Wild caught)', 'HOOK_AND_LINE', NULL, 'WWF highlights very high bycatch in Atlantic pelagic longlines, including protected seabirds, sharks, marine mammals, turtles and billfishes. Bluefin also occupies a high trophic level, so heavy fishing can affect wider food webs. These impacts support an Avoid rating.', 'A large, fast-swimming tuna that migrates across the open Atlantic and is highly valued in premium seafood markets.'),
  ('SF019', 'wwf-row-9', 'Atlantic Cod', NULL, 'Gadus Morhua', 'REDUCE', 'Russia (Barrent sea)', 'RU', 'WILD', 'Long lines/ gillnets (Wild caught)', 'GILLNET', NULL, 'WWF reports the North-East Arctic cod stock was healthy in its cited assessment and covered by a good management plan. Closures protect juveniles and management measures help control fishing and illegal, unreported and unregulated activity. Despite these positives, this Russian Barents Sea record is rated Reduce.', 'A cold-water cod species associated with northern Atlantic waters and valued for its mild, flaky flesh.'),
  ('SF020', 'wwf-row-10', 'Atlantic Salmon', NULL, 'Salmo salar', 'REDUCE', 'Norway', 'NO', 'FARMED', 'Floating net cages (Farmed)', 'AQUACULTURE', NULL, 'WWF explains that Norwegian floating net-pen salmon farms interact directly with marine waters. Waste, uneaten feed and antibiotics can affect sediments, while escapes, disease, parasites and chemical use can affect ecosystems. These environmental risks support a Reduce rating for this farmed record.', 'A widely farmed salmon with pink-orange flesh, raised in marine cages and commonly sold fresh or smoked.'),
  ('SF021', 'wwf-row-11', 'Bakulan', 'Skipjack', 'Katsuwonus pelamis', 'REDUCE', 'Malaysia (Sabah)', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Bakulan Reduce for the stated Malaysia (Sabah) Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small tropical tuna that travels in schools through warm ocean waters and is widely used in Southeast Asian fisheries.'),
  ('SF022', 'wwf-row-13', 'Bawal Emas', 'Snubnose Pompano', 'Trachinotus blochii', 'BEST_CHOICE', 'Malaysia (Peninsular)', 'MY', 'FARMED', 'Cage Culture (Farmed)', 'AQUACULTURE', NULL, 'WWF rates Malaysian Peninsular cage-cultured Bawal Emas Best Choice. The guide describes the species as associated with rocky and coral reefs and inshore habitats and notes its popularity in Malaysian aquaculture. Best Choice is reserved for preferred seafood from well-managed stocks or lower-impact aquaculture.', 'A warm-water pompano with a streamlined body, often associated with coastal waters and marine aquaculture.'),
  ('SF002', 'wwf-row-14', 'Bawal Hitam', 'Black Pomfret', 'Parastromateus niger', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Bawal Hitam Reduce for the stated Malaysia Trawl record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A deep-bodied pomfret with a distinctive dark body, commonly sold in Malaysian seafood markets.'),
  ('SF006', 'wwf-row-15', 'Bawal Putih', 'Chinese Silver Pomfret', 'Pampus chinensis', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Gillnets (Wild caught)', 'GILLNET', NULL, 'WWF notes Chinese Silver Pomfret is mainly caught by trawl. The guide describes trawling as highly detrimental because it is non-selective, can damage habitat and can create bycatch of endangered, threatened and protected species. These fishing-method impacts support an Avoid rating.', 'A silver-bodied pomfret found over muddy coastal seabeds and widely consumed across Asian markets.'),
  ('SF023', 'wwf-row-16', 'Belanak', 'Longfin Grey Mullet', 'Valamugil cunnesius', 'BEST_CHOICE', 'Malaysia', 'MY', 'WILD', 'Gillnets (Wild caught)', 'GILLNET', NULL, 'WWF rates Belanak Best Choice for the stated Malaysia Gillnets record. Best Choice is reserved for preferred seafood from well-managed, non-overexploited fisheries or lower-impact aquaculture. WWF therefore presents this record as a preferred seafood option.', 'A coastal mullet associated with estuaries and shallow waters, recognised for its elongated body and fine-textured flesh.'),
  ('SF024', 'wwf-row-17', 'Bulu Ayam (Ikan Masin)', 'Grenadler Anchovy', 'Coilia spp.', 'REDUCE', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Other Seine (Wild caught)', 'OTHER', NULL, 'WWF rates Bulu Ayam (Ikan Masin) Reduce for the stated Malaysia (Peninsular) Other Seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small anchovy-like fish used locally as dried or salted seafood and associated with Malaysian coastal fisheries.'),
  ('SF025', 'wwf-row-18', 'Bulus', 'Silver Sillago', 'Sillago sihama', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Bulus Avoid for the stated Malaysia Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A small silver fish that lives over sandy and muddy coastal bottoms and is commonly caught in nearshore fisheries.'),
  ('SF007', 'wwf-row-19', 'Cencaru', 'Hardtail Scad', 'Megalaspis cordyla', 'BEST_CHOICE', 'Malaysia', 'MY', 'WILD', 'Purse seine/ Gillnet Trawl (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Cencaru Best Choice for the stated Malaysia Purse seine/ Gillnet Trawl record. Best Choice is reserved for preferred seafood from well-managed, non-overexploited fisheries or lower-impact aquaculture. WWF therefore presents this record as a preferred seafood option.', 'A robust coastal scad that forms schools in tropical waters and is a familiar fish in Malaysian markets.'),
  ('SF026', 'wwf-row-20', 'Chinook Salmon', NULL, 'Oncorhynchus tshawytscha', 'BEST_CHOICE', 'Alaska', 'US', 'WILD', 'Pelagic gillnets (Wild caught)', 'GILLNET', NULL, 'WWF says cited Alaskan Chinook salmon fisheries are managed by the Alaska Department of Fish and Game and the stocks are healthy. Area-specific commercial regulations, Fishery Improvement Projects and partial MSC certification support management. These measures support the Best Choice classification for this fishery.', 'A large Pacific salmon known for its rich flavour and dark flesh, migrating between the ocean and freshwater rivers.'),
  ('SF027', 'wwf-row-22', 'Hoki', NULL, 'Macruronus novaezelandiae', 'REDUCE', 'New Zealand', 'NZ', 'WILD', 'Mid-water trawl (Wild caught)', 'TRAWL', NULL, 'WWF notes New Zealand hoki is caught with mid-water otter trawls. Bycatch and juvenile catch can be significant, and interactions with protected species may be high. Discards are low and seabed contact is unlikely, reducing habitat impact. The balance of risks and mitigations leads WWF to Reduce.', 'A long-bodied cold-water fish commonly caught around New Zealand and used widely as a white-fleshed seafood.'),
  ('SF028', 'wwf-row-23', 'Ikan Bilis', 'Anchovies', 'Stolephorus spp.', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine/ Lift nets (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Ikan Bilis Reduce for the stated Malaysia Purse seine/ Lift nets record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'Small schooling anchovies widely used fresh, dried or fermented in Malaysian cuisine and coastal food traditions.'),
  ('SF029', 'wwf-row-24', 'Ikan Delah / Tauhu', 'Yellowtail Fusiler', 'Caesio cuning', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Pelagic gillnets (Wild caught)', 'GILLNET', NULL, 'WWF describes this Malaysian fishery as data deficient, with limited stock and biological information. Given widespread overfishing across the Indo-Pacific, stocks are considered likely to be overfished or undergoing overfishing. Bottom-set gillnets can also be non-selective and affect protected species, supporting Avoid.', 'A colourful fusilier that forms schools around reefs and coastal waters, often encountered in tropical Southeast Asian fisheries.'),
  ('SF030', 'wwf-row-25', 'Ikan Gelama', 'Croakers', 'Sciaenidae spp.', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Bottom Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Ikan Gelama Avoid for the stated Malaysia Bottom Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A group of coastal croakers that often live near muddy bottoms and estuaries and produce characteristic drumming sounds.'),
  ('SF003', 'wwf-row-26', 'Ikan Merah', 'Red Snapper', 'Lutjanus sebae', 'REDUCE', 'Malaysia (East Coast)', 'MY', 'WILD', 'Hook and line (Wild caught)', 'HOOK_AND_LINE', NULL, 'WWF rates Ikan Merah Reduce for the stated Malaysia (East Coast & Hook and line record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A red snapper associated with reefs and coastal waters, known for firm flesh and a bright reddish body.'),
  ('SF031', 'wwf-row-27', 'Ikan Sebelah', 'Flounder', 'Pseudorhombus malayanus', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Ikan Sebelah Avoid for the stated Malaysia Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A bottom-dwelling flatfish with both eyes on one side of its body, living mainly over sandy or muddy seabeds.'),
  ('SF032', 'wwf-row-28', 'Ikan Selar', 'Common Scad', 'Decapterus akaadsi', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF notes Common Scad is a schooling species found in open water and around islands, often at roughly 40–200 metres. Stock health and species biology information is lacking, creating sustainability uncertainty. Purse seine is the common and more selective harvest method, supporting Reduce rather than Avoid.', 'A small schooling scad common in tropical waters and a familiar fish in Malaysian seafood markets.'),
  ('SF008', 'wwf-row-29', 'Jenahak', 'John''s Snapper', 'Lutjanus johnii', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF reports no stock assessments for John''s Snapper and high vulnerability to fishing pressure. Regional fisheries are considered significantly overfished, while bottom trawling can threaten turtles and damage corals and other benthic habitats. Juvenile and non-target catches are also concerns, supporting Avoid.', 'A snapper associated with coastal and reef habitats, recognised for its coppery-red body and firm flesh.'),
  ('SF033', 'wwf-row-30', 'Jerung / Yu', 'All Sharks', 'Elasmobranchii', 'AVOID', 'Malaysia and Global', 'MY', 'WILD', 'Trawl/ Hook and line (Wild caught)', 'TRAWL', NULL, 'WWF highlights overfishing and demand for shark fins and meat as major pressures on sharks. Sharks are also important predators in marine ecosystems. Given these conservation pressures and the Malaysia/global wild-caught context, WWF places the shark category in Avoid.', 'A broad group of sharks that occupy many marine habitats and play important roles as ocean predators.'),
  ('SF034', 'wwf-row-31', 'Kekacang', 'Pickhandle Barracuda', 'Sphyraena jello', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kekacang Avoid for the stated Malaysia Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A fast predatory barracuda found in tropical coastal waters, recognisable by its elongated body and strong jaws.'),
  ('SF001', 'wwf-row-32', 'Kembung / Pelaling', 'Indian Mackerel', 'Rastrelliger kanagurta', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Kembung / Pelaling Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small schooling mackerel widely eaten in Malaysia, with oily flesh and a strong place in everyday local cuisine.'),
  ('SF035', 'wwf-row-33', 'Kerapu Bebeh', 'Sixbar Grouper', 'Epinephelus sexfasciatus', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kerapu Bebeh Avoid for the stated Malaysia (Peninsular) Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A small grouper associated with reef and rocky coastal habitats and valued for its firm, white flesh.'),
  ('SF005', 'wwf-row-34', 'Kerapu Bintik', 'Orange Spotted Grouper', 'Epinephelus coioides', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Bottom Trawl (Wild caught)', 'TRAWL', NULL, 'WWF notes Orange Spotted Grouper uses mangroves, coral reefs, estuaries, shallow seas and saline lagoons. It is commonly caught by bottom trawl, which is highly detrimental because the gear is non-selective, can damage habitat and can create bycatch of protected species. These risks support Avoid.', 'A reef-associated grouper found in tropical coastal waters, commonly sold as a premium food fish in Southeast Asia.'),
  ('SF036', 'wwf-row-35', 'Kerapu Ekor Gelap', 'Duskytail Grouper', 'Epinephelus bleekeri', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kerapu Ekor Gelap Avoid for the stated Malaysia (Peninsular) Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A grouper associated with tropical coastal habitats, with a sturdy body and firm, white flesh.'),
  ('SF037', 'wwf-row-36', 'Kerapu Harimau', 'Brown-marble Grouper', 'Epinephelus fuscoguttatus', 'REDUCE', 'Malaysia (Peninsular)', 'MY', 'FARMED', 'Cage Culture (Farmed)', 'AQUACULTURE', NULL, 'WWF rates Kerapu Harimau Reduce for the stated Malaysia (Peninsular) Cage Culture record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A large, reef-associated grouper with a marbled pattern, commonly produced through marine cage aquaculture.'),
  ('SF038', 'wwf-row-37', 'Kerapu Kertang', 'Giant Grouper', 'Epinephelus lanceolatus', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'FARMED', 'Cage Culture (Farmed)', 'AQUACULTURE', NULL, 'WWF rates Kerapu Kertang Avoid for the stated Malaysia (Peninsular) Cage Culture record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A very large grouper that can inhabit reefs and coastal waters, reaching exceptional size compared with many groupers.'),
  ('SF039', 'wwf-row-38', 'Kerapu Lumpur', 'Malabar Grouper', 'Epinephelus malabaricus', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kerapu Lumpur Avoid for the stated Malaysia (Peninsular) Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A large tropical grouper associated with coastal and reef habitats and known for its firm, white flesh.'),
  ('SF040', 'wwf-row-39', 'Kerapu Sunoh / Kerapu Bara', 'Coral Trout / Leopard Coral Grouper', 'Plectropomus spp.', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Hook and line (Wild caught)', 'HOOK_AND_LINE', NULL, 'WWF describes this grouper fishery as data deficient, with no Malaysian stock assessments and major declines in fish productivity. The species is vulnerable to fishing pressure and linked to the high-value live reef fish trade. Although handline can be selective, removing reef predators can affect food webs and management is uneven, supporting Avoid.', 'A brightly coloured reef grouper associated with coral habitats and highly valued in Southeast Asian seafood markets.'),
  ('SF041', 'wwf-row-40', 'Kerapu Tikus', 'Humpback Grouper', 'Cromileptes altivelis', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'FARMED', 'Cage culture (Farmed)', 'AQUACULTURE', NULL, 'WWF rates Kerapu Tikus Avoid for the stated Malaysia (Peninsular) Cage culture record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A distinctive grouper with a rounded profile, associated with reef habitats and increasingly encountered in aquaculture.'),
  ('SF041', 'wwf-row-41', 'Kerapu Tikus', 'Humpback Grouper', 'Cromileptis altivelis', 'AVOID', 'Malaysia (Sabah)', 'MY', 'WILD', 'Cyanide', 'OTHER', NULL, 'WWF rates Kerapu Tikus Avoid for the stated Malaysia (Sabah) Cyanide record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A humpback grouper recognised by its distinctive head and body shape, associated with tropical reef environments.'),
  ('SF042', 'wwf-row-42', 'Kerepoh', 'Bigeye Trevally', 'Caranx sexfasciatus', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kerepoh Avoid for the stated Malaysia Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A large trevally with a powerful build, commonly found around coastal reefs and deeper tropical waters.'),
  ('SF009', 'wwf-row-43', 'Kerisi', 'Treadfin Breams', 'Nemipterus japiconus', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kerisi Reduce for the stated Malaysia Trawl record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small to medium coastal bream found over sandy or muddy bottoms and widely represented in Asian fisheries.'),
  ('SF043', 'wwf-row-44', 'Kikek', 'Ponyfish', 'Leiognathus spp.', 'REDUCE', 'Malaysia (Sabah)', 'MY', 'WILD', 'Lift Nets (WIld caught)', 'OTHER', NULL, 'WWF rates Kikek Reduce for the stated Malaysia (Sabah) Lift Nets record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'Small schooling ponyfish associated with coastal waters and sandy or muddy seabeds.'),
  ('SF044', 'wwf-row-45', 'Kunyit-kunyit', 'Brownstripe Red Snapper', 'Lutjanus vitta', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Kunyit-kunyit Avoid for the stated Malaysia Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A small red snapper associated with tropical coastal habitats and commonly caught by bottom-oriented fishing gears.'),
  ('SF045', 'wwf-row-46', 'Kurau', 'Striped Threadfin', 'Polydactylus plebeius', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Drift/ Gillnets (WIld caught)', 'GILLNET', NULL, 'WWF rates Kurau Reduce for the stated Malaysia Drift/ Gillnets record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A long-bodied threadfin that lives in coastal and estuarine waters and is valued for its firm flesh.'),
  ('SF046', 'wwf-row-47', 'Mameng', 'Humphead Wrasse', 'Cheilinus undulatus', 'AVOID', 'Malaysia (Sabah)', 'MY', 'WILD', 'Hook and line (Wild caught)', 'HOOK_AND_LINE', NULL, 'WWF identifies Humphead Wrasse as a long-lived, slow-breeding reef species. It is Endangered on the IUCN Red List and listed in CITES Appendix II. Overfishing, habitat destruction, cyanide fishing and fish bombing are major threats, making the Malaysian Sabah wild-caught record an Avoid choice.', 'A large, slow-growing wrasse closely associated with coral reefs and recognisable by its thick lips and hump-shaped head.'),
  ('SF047', 'wwf-row-48', 'Mata Besar / Lolong', 'Bigeye Scad', 'Selar crumenophthalmus', 'REDUCE', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Mata Besar / Lolong Reduce for the stated Malaysia (Peninsular) Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A schooling scad found in coastal and offshore waters and commonly landed in tropical Southeast Asian fisheries.'),
  ('SF048', 'wwf-row-49', 'Parang', 'Dorab Wolf-herring', 'Chirocentrus dorab', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'WILD', 'Trawl (Wild caught)', 'TRAWL', NULL, 'WWF rates Parang Avoid for the stated Malaysia (Peninsular) Trawl record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A long, slender marine predator with a streamlined body, often found in tropical coastal and open-water habitats.'),
  ('SF049', 'wwf-row-50', 'Pari', 'All Rays', 'Chondrichthyes', 'AVOID', 'Malaysia and Global', 'MY', 'WILD', 'Trawl/ Gillnets ((Wild caught)', 'TRAWL', NULL, 'WWF states overfishing is the largest threat to rays. Some ray fins enter the shark-fin trade, while ray and skate meat is also consumed. Because assessed fisheries use trawls and gillnets and cover vulnerable ray groups, WWF places this record in Avoid to reduce pressure on ray populations and marine ecosystems.', 'A broad group of rays with flattened bodies and wing-like fins, found across many marine habitats.'),
  ('SF050', 'wwf-row-51', 'Patin', 'Pangasius', 'Pangasius bocourti', 'BEST_CHOICE', 'Vietnam', 'VN', 'FARMED', 'Farmed', 'AQUACULTURE', 'ASC', 'WWF rates Vietnamese farmed Pangasius Best Choice and records Aquaculture Stewardship Council certification. Best Choice is for preferred seafood from well-managed stocks or lower-impact aquaculture. For this record, farmed production combined with ASC certification supports the preferred-choice rating and provides an additional signal of responsible farming and traceability.', 'A freshwater catfish farmed widely in Southeast Asia, valued for its mild flavour and soft, white flesh.'),
  ('SF010', 'wwf-row-52', 'Pelata', 'Blackfin Scad', 'Alepes melanoptera', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Pelata Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small tropical scad that forms schools in coastal waters and is commonly caught by purse seine fisheries.'),
  ('SF011', 'wwf-row-53', 'Selar Kuning', 'Yellowtail Scad', 'Selaroides leptolepis', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Demersal gillnets (Wild caught)', 'GILLNET', NULL, 'WWF describes this fishery as very data deficient, with biology and vulnerability to fishing mortality not well assessed. Given widespread overfishing in the Indo-Pacific and Malaysia/Indonesia, stocks are considered likely to be overfished. Bottom-set gillnets can also be non-selective and affect protected species, supporting Avoid.', 'A small yellow-tailed scad associated with tropical coastal waters and commonly caught in nearshore fisheries.'),
  ('SF051', 'wwf-row-54', 'Siakap Merah', 'Mangrove Red Snapper', 'Lutjanus argentimaculatus', 'AVOID', 'Malaysia (Peninsular)', 'MY', 'FARMED', 'Cage/ Pond culture (Farmed)', 'AQUACULTURE', NULL, 'WWF rates Malaysian Peninsular Mangrove Red Snapper Avoid for cage/pond culture and points consumers toward WWF-Malaysia''s Aquaculture Improvement Project. The S.O.S. Guide gives no longer species-specific explanation for this entry, so the user-facing context should focus on the higher-risk conventional farming pathway and the improved AIP alternative.', 'A mangrove-associated snapper that can live in estuaries and coastal waters and is valued as a food fish.'),
  ('SF014', 'wwf-row-55', 'Siakap Putih', 'Asian seabass / Barramundi', 'Lates calcarifer', 'AVOID', 'Malaysia', 'MY', 'FARMED', 'Pond culture (Farmed)', 'AQUACULTURE', NULL, 'WWF highlights risks in Malaysian barramundi pond farming, including soil fertility and salinisation effects on soil and water. Some farms also depend on trash fish, creating high Fish Feed Dependency Ratios. Although ponds can reduce disease risk versus open cages, WWF still rates this record Avoid and points to AIP alternatives.', 'A versatile Asian seabass found in estuaries, coastal waters and farms, known for its mild flavour and firm flesh.'),
  ('SF052', 'wwf-row-56', 'Tamban / Sardin', 'Sardine', 'Spratelloides gracilis', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Tamban / Sardin Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small schooling sardine associated with warm coastal waters and widely used as a food fish in Southeast Asia.'),
  ('SF012', 'wwf-row-57', 'Tenggiri', 'Narrow-barred Spanish Mackerel', 'Scomberomorus commerson', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Hook and line (WIld caught)', 'HOOK_AND_LINE', NULL, 'WWF assesses the same Narrow-barred Spanish Mackerel differently by fishing method. Hook-and-line is highly selective with lower bycatch and discards, so that record is Reduce; the gillnet record is Avoid. WWF also notes the species is Near Threatened, stocks are not fully assessed across its range and catch data are limited.', 'A large, fast-swimming mackerel with firm flesh, widely consumed in Malaysia and other tropical Asian markets.'),
  ('SF012', 'wwf-row-58', 'Tenggiri', 'Narrow-barred Spanish Mackerel', 'Scomberomorus commerson', 'AVOID', 'Malaysia', 'MY', 'WILD', 'Gillnets (Wild caught)', 'GILLNET', NULL, 'WWF rates Tenggiri Avoid for the stated Malaysia Gillnets record. Avoid covers unsustainable or overfished fisheries and aquaculture systems with negative environmental impacts. SukaSeafood should communicate this as a high-risk choice without adding unsupported reasons.', 'A large, fast-swimming mackerel with firm flesh, widely consumed in Malaysia and other tropical Asian markets.'),
  ('SF053', 'wwf-row-59', 'Terubok', 'Longtail Shad', 'Tenualosa macrura', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Gillnets (Wild caught)', 'GILLNET', NULL, 'WWF rates Terubok Reduce for the stated Malaysia Gillnets record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A long-bodied shad associated with coastal waters and river-influenced habitats, important in regional fisheries.'),
  ('SF004', 'wwf-row-60', 'Tilapia', 'Tilapia', 'Oreochromis Niloticus', 'REDUCE', 'Malaysia', 'MY', 'FARMED', 'Cage/ Pond culture (Farmed)', 'AQUACULTURE', NULL, 'WWF provides two Malaysian tilapia assessments. The general cage/pond-culture record is Reduce, while the Hulu Perak cage-culture record is Best Choice and ASC certified. WWF notes ASC-certified tilapia is available from Tasik Temenggor, Perak, showing that production location and responsible farming practices can materially change the sustainability assessment.', 'A hardy freshwater tilapia commonly farmed for its mild flavour, firm flesh and adaptable production conditions.'),
  ('SF004', 'wwf-row-61', 'Tilapia', 'Tilapia', 'Oreochromis Niloticus', 'BEST_CHOICE', 'Malaysia (Hulu Perak)', 'MY', 'FARMED', 'Cage Culture (Farmed)', 'AQUACULTURE', 'ASC', 'WWF rates Tilapia Best Choice for the stated Malaysia (Hulu Perak) Cage Culture record. Best Choice is reserved for preferred seafood from well-managed, non-overexploited fisheries or lower-impact aquaculture. WWF therefore presents this record as a preferred seafood option.', 'A farmed Nile tilapia associated with freshwater culture systems and valued as an accessible, mild-flavoured food fish.'),
  ('SF015', 'wwf-row-62', 'Tongkol', 'Longtail Tuna', 'Thunnus tonggol', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Tongkol Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A tropical tuna that lives in coastal and offshore waters and is widely used in Southeast Asian fisheries.'),
  ('SF054', 'wwf-row-63', 'Tongkol Kurik', 'Eastern Little Tuna', 'Euthynnus affinis', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Tongkol Kurik Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small tropical tuna with firm flesh, commonly found in warm coastal and offshore waters.'),
  ('SF055', 'wwf-row-64', 'Tongkol Selasih', 'Frigate Tuna', 'Auxis thazard', 'REDUCE', 'Malaysia', 'MY', 'WILD', 'Purse seine (Wild caught)', 'PURSE_SEINE', NULL, 'WWF rates Tongkol Selasih Reduce for the stated Malaysia Purse seine record. Reduce covers fisheries at risk of becoming unsustainable or aquaculture with environmental risks. Consumers are advised to eat it occasionally when Best Choice options are unavailable.', 'A small tuna species found in warm ocean waters, recognised by its compact body and strong swimming ability.')
) AS v(code, source_record_key, common_name_raw, secondary_common_name_raw,
       scientific_name_raw, rating, origin_raw, origin_code, production_type,
       production_method_raw, production_method_code, certification_raw,
       context, notes_raw)
ON CONFLICT (wwf_assessment_id) DO UPDATE SET
  rating                     = EXCLUDED.rating,
  common_name_raw            = EXCLUDED.common_name_raw,
  secondary_common_name_raw  = EXCLUDED.secondary_common_name_raw,
  scientific_name_raw        = EXCLUDED.scientific_name_raw,
  origin_raw                 = EXCLUDED.origin_raw,
  origin_code                = EXCLUDED.origin_code,
  production_type            = EXCLUDED.production_type,
  production_method_raw      = EXCLUDED.production_method_raw,
  production_method_code     = EXCLUDED.production_method_code,
  certification_raw          = EXCLUDED.certification_raw,
  context                    = EXCLUDED.context,
  notes_raw                  = EXCLUDED.notes_raw;

COMMIT;
