-- =========================================================
-- 18_cooking_54.sql   ** GENERATED FILE — DO NOT EDIT **
-- =========================================================
-- Regenerate with:  cd backend && python scripts/generate_cooking_54.py
-- Source: data/SuitabilityScoreSuka_complete_54_fish.csv
-- 54 WWF-listed fishes x 7 methods. Mapped by fish_name; CSV UUIDs unused.
-- SF013 Demuduk is not in this file.

BEGIN;

INSERT INTO source_snapshot (
  source_snapshot_id, data_source_id, version_label,
  retrieved_at, collection_method, manifest, notes
) VALUES (
  suka_uuid5('source_snapshot:team_curated:cooking-54-20260914'),
  suka_uuid5('data_source:team_curated'),
  'cooking-54-20260914',
  TIMESTAMPTZ '2026-09-14 00:00:00+00',
  'TEAM_CURATED',
  '{"files": ["SuitabilityScoreSuka_complete_54_fish.csv"]}'::jsonb,
  'Cooking suitability for the 54 WWF-listed fishes. Scores and reasons '
  'come from the retrieved CSV, keyed onto suka_uuid5 seafood_item and '
  'cooking_method ids. CSV UUIDs are not used.'
)
ON CONFLICT (source_snapshot_id) DO UPDATE SET
  version_label = EXCLUDED.version_label,
  retrieved_at  = EXCLUDED.retrieved_at,
  notes         = EXCLUDED.notes,
  manifest      = EXCLUDED.manifest;

INSERT INTO cooking_suitability (
  cooking_suitability_id, seafood_item_id, cooking_method_id, source_snapshot_id,
  suitability_score, reason_en, reason_ms, updated_at
)
SELECT
  suka_uuid5('cooking_suitability:' || v.code || ':' || v.method),
  suka_uuid5('seafood_item:' || v.code),
  suka_uuid5('cooking_method:' || v.method),
  suka_uuid5('source_snapshot:team_curated:cooking-54-20260914'),
  v.score::smallint,
  v.reason_en,
  v.reason_ms,
  TIMESTAMPTZ '2026-09-14 00:00:00+00'
FROM (VALUES
  ('SF001', 'GRILL', 5, 'Oily flesh bastes itself over coals and the skin crisps without sticking.', 'Isinya berminyak, tidak melekat pada panggangan dan kulitnya rangup.'),
  ('SF001', 'STEAM', 2, 'The strong flavour overwhelms the delicate seasoning steaming relies on.', 'Rasanya terlalu kuat untuk perasa halus masakan kukus.'),
  ('SF001', 'FRY', 4, 'Small whole fish fry quickly and evenly.', 'Ikan kecil mudah digoreng sekata.'),
  ('SF001', 'CURRY', 5, 'Firm enough to hold its shape in a long-simmered gulai or asam pedas.', 'Cukup padat untuk kekal utuh dalam gulai atau asam pedas.'),
  ('SF001', 'SOUP', 3, 'Usable, though the oil can cloud a clear broth.', 'Boleh digunakan, tetapi minyaknya boleh mengeruhkan sup jernih.'),
  ('SF001', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF001', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF002', 'GRILL', 3, 'Possible, but direct heat dries the lean flesh quickly.', 'Boleh, tetapi panas terus cepat mengeringkan isinya yang tidak berlemak.'),
  ('SF002', 'STEAM', 5, 'The festive steamed fish: fine white flesh, very few bones.', 'Ikan kukus perayaan: isi putih halus, tulang sangat sedikit.'),
  ('SF002', 'FRY', 4, 'Flat body crisps evenly, though it is an expensive fish to fry.', 'Badan leper menjadi rangup sekata, tetapi mahal untuk digoreng.'),
  ('SF002', 'CURRY', 2, 'Heavy spice buries the delicate flavour you paid for.', 'Rempah pekat menenggelamkan rasa halus yang mahal ini.'),
  ('SF002', 'SOUP', 3, 'Makes a clean, delicate broth.', 'Menghasilkan sup jernih yang halus rasanya.'),
  ('SF002', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF002', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF003', 'GRILL', 5, 'Thick steaks take direct heat without breaking up.', 'Kepingan tebal tahan panas terus tanpa hancur.'),
  ('SF003', 'STEAM', 5, 'Firm white flesh stays intact and stays moist — the default treatment.', 'Isi putih padat kekal utuh dan lembap — cara paling biasa.'),
  ('SF003', 'FRY', 3, 'Fine, but frying a whole snapper is an expensive way to cook it.', 'Boleh, tetapi menggoreng jenahak utuh membazir.'),
  ('SF003', 'CURRY', 4, 'Holds its shape through a long-simmered gulai.', 'Kekal utuh dalam gulai yang direneh lama.'),
  ('SF003', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF003', 'BAKE', 4, 'Good baked whole; the skin protects the flesh.', 'Sesuai dibakar utuh; kulitnya melindungi isi.'),
  ('SF003', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF004', 'GRILL', 4, 'Mild flesh takes on marinade and smoke well.', 'Isi lembut menyerap perapan dan asap dengan baik.'),
  ('SF004', 'STEAM', 3, 'Fine steamed, but freshwater earthiness needs strong ginger.', 'Boleh dikukus, tetapi bau tanah air tawar perlu banyak halia.'),
  ('SF004', 'FRY', 5, 'The default weeknight fry: mild, cheap, cooks through fast.', 'Gorengan harian: rasa lembut, murah, cepat masak.'),
  ('SF004', 'CURRY', 4, 'Neutral flavour absorbs whatever gravy it sits in.', 'Rasa neutral menyerap kuah dengan baik.'),
  ('SF004', 'SOUP', 4, 'Common in clear fish soup; the flesh does not break up.', 'Biasa dalam sup ikan jernih; isinya tidak hancur.'),
  ('SF004', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF004', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF005', 'GRILL', 4, 'Firm steaks grill cleanly without drying.', 'Kepingan padat dipanggang tanpa menjadi kering.'),
  ('SF005', 'STEAM', 5, 'Premium steamed kerapu — the preparation the price is for.', 'Kerapu kukus premium — cara masakan yang berbaloi dengan harganya.'),
  ('SF005', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF005', 'CURRY', 2, 'Technically fine, but heavy spice buries an expensive fish.', 'Boleh, tetapi rempah pekat menenggelamkan ikan mahal ini.'),
  ('SF005', 'SOUP', 4, 'Bones make an unusually rich stock.', 'Tulangnya menghasilkan sup yang sangat berperisa.'),
  ('SF005', 'BAKE', 3, 'Works wrapped and baked whole.', 'Sesuai dibalut dan dibakar utuh.'),
  ('SF005', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF006', 'GRILL', 3, 'Workable, but grilling wastes what you paid a premium for.', 'Boleh, tetapi memanggang membazirkan kelebihan ikan mahal ini.'),
  ('SF006', 'STEAM', 5, 'The classic steamed pomfret: few bones, flesh that flakes cleanly.', 'Bawal kukus klasik: tulang sedikit, isi mudah dileraikan.'),
  ('SF006', 'FRY', 4, 'Flat body crisps evenly in a shallow pan.', 'Badan leper menjadi rangup sekata dalam kuali cetek.'),
  ('SF006', 'CURRY', 3, 'Holds up in gravy, though the delicate flavour is lost.', 'Tahan dalam kuah, tetapi rasa halusnya hilang.'),
  ('SF006', 'SOUP', 4, 'Bones and head give a clear soup real body.', 'Tulang dan kepala memberi sup jernih rasa yang mantap.'),
  ('SF006', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF006', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF007', 'GRILL', 4, 'Firm dark flesh takes coals well and does not fall apart.', 'Isi gelap yang padat sesuai dipanggang dan tidak hancur.'),
  ('SF007', 'STEAM', 2, 'Too strongly flavoured for steaming.', 'Rasanya terlalu kuat untuk dikukus.'),
  ('SF007', 'FRY', 5, 'The classic cencaru sumbat: split, stuffed with sambal, fried whole.', 'Cencaru sumbat klasik: dibelah, disumbat sambal, digoreng utuh.'),
  ('SF007', 'CURRY', 4, 'Dense enough to survive a long simmer in asam pedas.', 'Cukup padat untuk direneh lama dalam asam pedas.'),
  ('SF007', 'SOUP', 2, 'Strong oily flavour clouds a clear soup.', 'Rasa berminyaknya mengeruhkan sup jernih.'),
  ('SF007', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF007', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF008', 'GRILL', 4, 'Thick steaks take direct heat without falling apart.', 'Kepingan tebal tahan panas terus tanpa hancur.'),
  ('SF008', 'STEAM', 5, 'Firm white flesh stays intact and stays moist.', 'Isi putih padat kekal utuh dan lembap.'),
  ('SF008', 'FRY', 4, 'Fillets hold together well in the pan.', 'Isi filet kekal utuh dalam kuali.'),
  ('SF008', 'CURRY', 4, 'Dense flesh survives a long simmer in rich gravy.', 'Isi padat tahan direneh lama dalam kuah pekat.'),
  ('SF008', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF008', 'BAKE', 3, 'Good whole-baked, though it dries if overcooked.', 'Sesuai dibakar utuh, tetapi kering jika terlebih masak.'),
  ('SF008', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF009', 'GRILL', 2, 'Thin body dries out before the skin colours.', 'Badan nipis menjadi kering sebelum kulitnya perang.'),
  ('SF009', 'STEAM', 3, 'Workable, though it is bony for steaming.', 'Boleh, tetapi banyak tulang untuk dikukus.'),
  ('SF009', 'FRY', 5, 'Small enough to fry whole and eat off the bone.', 'Cukup kecil untuk digoreng utuh dan dimakan terus dari tulang.'),
  ('SF009', 'CURRY', 4, 'A standard everyday gulai fish.', 'Ikan gulai harian yang biasa.'),
  ('SF009', 'SOUP', 4, 'Sweet flesh and plenty of bone make a good clear soup.', 'Isi manis dan banyak tulang menghasilkan sup jernih yang sedap.'),
  ('SF009', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF009', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF010', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF010', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF010', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF010', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF010', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF010', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF010', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF011', 'GRILL', 3, 'Grills acceptably, but is more usually fried.', 'Boleh dipanggang, tetapi lebih biasa digoreng.'),
  ('SF011', 'STEAM', 2, 'Too small and too strongly flavoured to steam well.', 'Terlalu kecil dan rasanya terlalu kuat untuk dikukus.'),
  ('SF011', 'FRY', 5, 'The everyday fried fish: cheap, small, crisp in minutes.', 'Ikan goreng harian: murah, kecil, rangup dalam beberapa minit.'),
  ('SF011', 'CURRY', 4, 'Common in a quick weekday gulai or asam pedas.', 'Biasa dalam gulai atau asam pedas harian.'),
  ('SF011', 'SOUP', 3, 'Adds flavour, though small bones are a nuisance.', 'Menambah rasa, tetapi tulang halusnya menyusahkan.'),
  ('SF011', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF011', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF012', 'GRILL', 5, 'Thick firm steaks are made for direct heat.', 'Kepingan tebal dan padat sangat sesuai untuk panggangan.'),
  ('SF012', 'STEAM', 2, 'Dense steaks turn dry and fibrous when steamed.', 'Kepingan padat menjadi kering dan berserabut apabila dikukus.'),
  ('SF012', 'FRY', 4, 'Steaks fry well; also the fish used for otak-otak and keropok.', 'Kepingan sesuai digoreng; juga ikan untuk otak-otak dan keropok.'),
  ('SF012', 'CURRY', 5, 'The standard fish for gulai and asam pedas; steaks hold together.', 'Ikan gulai dan asam pedas yang standard; kepingannya kekal utuh.'),
  ('SF012', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF012', 'BAKE', 3, 'Good baked, but dries if taken past done.', 'Sesuai dibakar, tetapi kering jika terlebih masak.'),
  ('SF012', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF014', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF014', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF014', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF014', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF014', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF014', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF014', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF015', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF015', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF015', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF015', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF015', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF015', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF015', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF016', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF016', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF016', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF016', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF016', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF016', 'BAKE', 5, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF016', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF017', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF017', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF017', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF017', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF017', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF017', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF017', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF018', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF018', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF018', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF018', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF018', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF018', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF018', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF019', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF019', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF019', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF019', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF019', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF019', 'BAKE', 5, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF019', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF020', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF020', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF020', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF020', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF020', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF020', 'BAKE', 5, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF020', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF021', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF021', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF021', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF021', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF021', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF021', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF021', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF022', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF022', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF022', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF022', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF022', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF022', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF022', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF023', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF023', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF023', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF023', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF023', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF023', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF023', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF024', 'GRILL', 2, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF024', 'STEAM', 1, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF024', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF024', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF024', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF024', 'BAKE', 2, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF024', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF025', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF025', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF025', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF025', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF025', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF025', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF025', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF026', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF026', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF026', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF026', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF026', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF026', 'BAKE', 5, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF026', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF027', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF027', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF027', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF027', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF027', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF027', 'BAKE', 5, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF027', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF028', 'GRILL', 1, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF028', 'STEAM', 1, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF028', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF028', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF028', 'SOUP', 5, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF028', 'BAKE', 2, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF028', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF029', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF029', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF029', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF029', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF029', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF029', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF029', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF030', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF030', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF030', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF030', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF030', 'SOUP', 5, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF030', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF030', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF031', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF031', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF031', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF031', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF031', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF031', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF031', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF032', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF032', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF032', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF032', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF032', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF032', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF032', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF033', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF033', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF033', 'FRY', 2, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF033', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF033', 'SOUP', 2, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF033', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF033', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF034', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF034', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF034', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF034', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF034', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF034', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF034', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF035', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF035', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF035', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF035', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF035', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF035', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF035', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF036', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF036', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF036', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF036', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF036', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF036', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF036', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF037', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF037', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF037', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF037', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF037', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF037', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF037', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF038', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF038', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF038', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF038', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF038', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF038', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF038', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF039', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF039', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF039', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF039', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF039', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF039', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF039', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF040', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF040', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF040', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF040', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF040', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF040', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF040', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF041', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF041', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF041', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF041', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF041', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF041', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF041', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF042', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF042', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF042', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF042', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF042', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF042', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF042', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF043', 'GRILL', 2, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF043', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF043', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF043', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF043', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF043', 'BAKE', 2, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF043', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF044', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF044', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF044', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF044', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF044', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF044', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF044', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF045', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF045', 'STEAM', 4, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF045', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF045', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF045', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF045', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF045', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF046', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF046', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF046', 'FRY', 2, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF046', 'CURRY', 3, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF046', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF046', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF046', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF047', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF047', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF047', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF047', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF047', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF047', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF047', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF048', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF048', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF048', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF048', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF048', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF048', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF048', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF049', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF049', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF049', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF049', 'CURRY', 5, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF049', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF049', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF049', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF050', 'GRILL', 3, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF050', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF050', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF050', 'CURRY', 5, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF050', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF050', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF050', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF051', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF051', 'STEAM', 5, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF051', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF051', 'CURRY', 5, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF051', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF051', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF051', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF052', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF052', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF052', 'FRY', 5, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF052', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF052', 'SOUP', 4, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF052', 'BAKE', 3, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF052', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF053', 'GRILL', 4, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF053', 'STEAM', 3, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF053', 'FRY', 4, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF053', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF053', 'SOUP', 5, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF053', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF053', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF054', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF054', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF054', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF054', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF054', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF054', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF054', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.'),
  ('SF055', 'GRILL', 5, 'Firm or naturally rich flesh holds up well over direct heat.', 'Isi yang padat atau berlemak tahan dimasak terus di atas api.'),
  ('SF055', 'STEAM', 2, 'Gentle heat preserves moisture and suits the fish''s texture.', 'Haba lembut membantu mengekalkan kelembapan dan tekstur isi.'),
  ('SF055', 'FRY', 3, 'Crisps well in the pan and suits whole-fish or firm cuts.', 'Sesuai digoreng kerana tekstur atau saiznya membantu menghasilkan hasil yang rangup.'),
  ('SF055', 'CURRY', 4, 'Works well in rich gravy and holds its shape during simmering.', 'Sesuai dalam kuah kerana isi kekal baik semasa direneh.'),
  ('SF055', 'SOUP', 3, 'Its bones, head or flavour can add useful body to a broth.', 'Tulang, kepala atau rasa ikan membantu memberikan badan pada sup.'),
  ('SF055', 'BAKE', 4, 'Works well with enclosed oven heat, especially as a whole fish or thick cut.', 'Sesuai dibakar, terutama sebagai ikan seekor atau potongan tebal.'),
  ('SF055', 'RAW', 1, 'Not recommended by default without sashimi-grade handling and traceability.', 'Tidak disyorkan secara lalai tanpa pengendalian dan kebolehkesanan gred sashimi.')
) AS v(code, method, score, reason_en, reason_ms)
ON CONFLICT (cooking_suitability_id) DO UPDATE SET
  suitability_score = EXCLUDED.suitability_score,
  reason_en         = EXCLUDED.reason_en,
  reason_ms         = EXCLUDED.reason_ms,
  source_snapshot_id = EXCLUDED.source_snapshot_id,
  updated_at        = EXCLUDED.updated_at;

DO $$
DECLARE
  n_rows INT;
  n_missing INT;
BEGIN
  SELECT count(*) INTO n_rows
    FROM cooking_suitability c
    JOIN seafood_item s USING (seafood_item_id)
    JOIN source_snapshot snap ON snap.source_snapshot_id = c.source_snapshot_id
   WHERE snap.version_label = 'cooking-54-20260914';
  IF n_rows <> 378 THEN
    RAISE EXCEPTION 'expected 378 cooking rows for the 54 WWF fishes, found %', n_rows;
  END IF;

  SELECT count(*) INTO n_missing
    FROM seafood_item s
   WHERE s.active
     AND s.code <> 'SF013'
     AND NOT EXISTS (
           SELECT 1 FROM cooking_suitability c
            WHERE c.seafood_item_id = s.seafood_item_id
         );
  IF n_missing > 0 THEN
    RAISE EXCEPTION '% active species have no cooking_suitability rows', n_missing;
  END IF;
END $$;

COMMIT;
